# QCA-ALL.yml
name: QCA-ALL

#CI计划
on:
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        CONFIG: [IPQ60XX-WIFI-YES]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: OWRT
      #默认WIFI名称
      WRT_SSID: Glinet-AXT1800
      #默认WIFI密码
      WRT_WORD: 23679164329
      #默认地址
      WRT_IP: 192.168.1.1
      #默认密码，仅作提示，修改无用
      WRT_PW: 无
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      #插件调整
      WRT_PACKAGE: |
        ${{inputs.PACKAGE}}
        # 在这里添加 fancontrol 软件包的名称，例如：
        luci-app-fancontrol
      # === 添加以下新的输入参数 ===
      WRT_CUSTOM_FEEDS: |
        src-git fancontrol https://github.com/JiaY-shi/fancontrol.git
      # =============================
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
